---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

environments:
    development:
        dataSource:
            dbCreate: 'create'
            url: 'jdbc:postgresql://127.0.0.1:5432/sandbox'
            driverClassName: 'org.postgresql.Driver'
            dialect: 'org.hibernate.dialect.PostgreSQLDialect'
            username: 'sandbox'
            password: 'sandbox'
            logSql: true

---
---
grails:
    profile: web
    codegen:
        defaultPackage: 'example'
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    app:
        context: '/'
    plugin:
            springsecurity:
                auth:
                    loginFormUrl: '/login/auth'
                apf:
                    filterProcessesUrl: '/login/authenticate'
                    usernameParameter: 'username'
                    passwordParameter: 'password'
                    postOnly: false
                logout:
                    filterProcessesUrl: '/login/logoff'
                    postOnly: false
                password:
                    algorithm: 'bcrypt'
                    bcrypt:
                        logrounds: 15
                rejectIfNoRule: true
                fii:
                    rejectPublicInvocations: false
                userLookup:
                    userDomainClassName: 'example.User'
                    authorityJoinClassName: 'example.UserRole'
                authority:
                    className: 'example.Role'
                securityConfigType: "InterceptUrlMap"
                interceptUrlMap:
                    - pattern: '/assets/**'
                      access:
                          - 'permitAll'
                    - pattern: '/static/**'
                      access:
                          - 'permitAll'
                    - pattern: '/**/js/**'
                      access:
                          - 'permitAll'
                    - pattern: '/**/css/**'
                      access:
                          - 'permitAll'
                    - pattern: '/**/images/**'
                      access:
                          - 'permitAll'
                    - pattern: '/**/favicon.ico'
                      access:
                          - 'permitAll'
                    - pattern: '/login/**'
                      access:
                          - 'permitAll'
                    - pattern: '/message/**'
                      access:
                          - 'ROLE_STAFF'
                    - pattern: '/stomp/**'
                      access:
                          - 'ROLE_STAFF'
                    - pattern: '/**'
                      access:
                          - 'permitAll'
                filterChain:
                    chainMap:
                        - pattern: '/message/**'
                          filters: 'JOINED_FILTERS'
                        - pattern: '/login/**'
                          filters: 'JOINED_FILTERS'
                        - pattern: '/stomp/**'
                          filters: 'JOINED_FILTERS'
                        - pattern: '/**'
                          filters: 'none'
                providerNames:
                    - 'rememberMeAuthenticationProvider'
                    - 'anonymousAuthenticationProvider'
                    - 'daoAuthenticationProvider'
endpoints:
    jmx:
        unique-names: true
